before_script:
  - yarn

services:
  - name: postgres:9
    alias: postgres

variables:
  POSTGRES_DB: fewer-test
  POSTGRES_USER: fewer-test
  POSTGRES_PASSWORD: ""
  IN_CI: "true"

node8:
  image: node:8-alpine
  script:
    - yarn test
    - PGHOST=postgres PGDATABASE=fewer-test PGUSER=fewer-test PGPASSWORD="" yarn lerna run integration

node10:
  image: node:10-alpine
  script:
    - yarn test
    - PGHOST=postgres PGDATABASE=fewer-test PGUSER=fewer-test PGPASSWORD="" yarn lerna run integration

latest:
  stage: test
  image: node:alpine
  allow_failure: true
  script:
    - yarn test
    - PGHOST=postgres PGDATABASE=fewer-test PGUSER=fewer-test PGPASSWORD="" yarn lerna run integration
