before_script:
  - yarn

services:
  - name: postgres:9
    alias: postgres

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  IN_CI: "true"

node8:
  image: node:8-alpine
  script:
    - yarn test
    - PGHOST=postgres PGDATABASE=postgres PGUSER=postgres PGPASSWORD=password yarn lerna run integration

node10:
  image: node:10-alpine
  script:
    - yarn test
    - PGHOST=postgres PGDATABASE=postgres PGUSER=postgres PGPASSWORD=password yarn lerna run integration

latest:
  stage: test
  image: node:alpine
  allow_failure: true
  script:
    - yarn test
    - PGHOST=postgres PGDATABASE=postgres PGUSER=postgres PGPASSWORD=password yarn lerna run integration
