version: '3'
services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=password

    app:
        volumes:
            - ../../:/app
        build: ../../
        working_dir: /app/packages/adapter-postgres/
        command: yarn run integration
        depends_on:
            - db
